### ISSUE TITLE
Rspec tests for `st2api` and `st2auth` ports

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#103]
Ensure that `st2api` and `st2auth` are running on corresponding ports.

Could be useful for cases like this: https://github.com/StackStorm/st2-packages/pull/100#issuecomment-174528708 to identify the problem better.

Overall good check to have.

**Comment by dennybaa** [comment]
Also I'd like to remind, if you are going to something more fundamental than this. Then it should be suspended not to make double work. The fact is that the current specs are SO UGLY, that they should be replaced completely https://github.com/StackStorm/st2-packages/blob/master/Rakefile#L35-L39 :)
