### ISSUE TITLE
st2 services logs are in DEBUG level. Set them to INFO by default. Same for mistral.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2-packages#112]

**Comment by lakshmi-kannan** [comment]
So I wanted to make this change and it looks like the change needs to happen in actual st2 repo. https://github.com/StackStorm/st2/blob/master/st2reactor/conf/logging.sensorcontainer.conf#L11

Can we copy all those logging.conf files to conf/ directory in packages? I am split on this personally. Having two places of truth is bad. I'd like to hear y'all's opinions.

**Comment by armab** [comment]
Closed via https://github.com/StackStorm/st2-packages/pull/131
