### ISSUE TITLE
Mistral sometimes doesn't listen on `8989` after moving to `gunicorn`

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#113]
![0prdztz 1](https://cloud.githubusercontent.com/assets/1533818/12594166/5d84d3da-c47d-11e5-8fca-bb361792557b.png)

I retried builds several times and got always different results. See the builds: 
* https://circleci.com/gh/StackStorm/st2-packages/283
  - `mistral` failed on `wheezy` and `jessie`
* https://circleci.com/gh/StackStorm/st2-packages/284
  - `mistral` + `st2auth` failed on `wheezy`
  - `mistral` failed on `jessie`
* https://circleci.com/gh/StackStorm/st2-packages/285
  - `mistral` failed on `wheezy` and `jessie`

It looks like very similar to ghost bug we have after adding `gunicorn` for both `st2api` and `st2auth`: https://github.com/StackStorm/st2-packages/issues/106

----
Actually, same thing. Here `mistral` just fails almost every time.

Good to debug tomorrow in Circle + SSH, to understand what's happening inside, since we have it more reproducible. For now stats are the following: 
* `st2auth` or `st2api` fails on `jessie` only
* `mistral` fails on both `wheezy` and `jessie`
* `trusty`, `el6`, `el7` are always OK.

**Comment by dennybaa** [comment]
gunicorn starts slowly, you should increase timeout, imo.

**Comment by dennybaa** [comment]
actually wrong conf substitution `/etc/default/mistral` for debian. el6 el7 are always OK, since that PR doesn't bring init files for rhel)

**Comment by dennybaa** [comment]
https://github.com/StackStorm/st2-packages/commit/6c5683902c03cbbfddc093ecffc088e7fce98671

**Comment by armab** [comment]
Sadly, it's still there: https://circleci.com/gh/StackStorm/st2/491
Latest `st2` & `st2packages` codebase, `ST2_WAITFORSTART` is set to `15 sec`, `mistral` failed under `jessie`.

Same as `st2auth` and `st2api` after moving to `gunicorn`. Still investigating.

**Comment by armab** [comment]
Related (but could be the same issue actually): https://github.com/StackStorm/st2-packages/issues/119

**Comment by armab** [comment]
@dennybaa confirmed https://github.com/StackStorm/st2-packages/issues/122 fixed the issue, closing.
