### ISSUE TITLE
Generate SSH keys for System User, add to sudoers and so on

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#117]
We currently ensure in packages that system user aka `stanley` is created on first install, see: 
* deb - https://github.com/StackStorm/st2-packages/blob/master/packages/st2bundle/debian/preinst#L13-L21
* rpm - https://github.com/StackStorm/st2-packages/blob/master/packages/st2bundle/rpm/st2bundle.spec#L41-L47

For sure we can extend that story, add to sudoers, generate default keys only for first/fresh install and so on. Detailed bash instructions: https://gist.github.com/lakshmi-kannan/85b03a6f1b489167c91b

@lakshmi-kannan request: https://stackstorm.slack.com/archives/packages/p1453869869000398

**Comment by lakshmi-kannan** [comment]
Regarding SSH script, no changes required in packages. We’ll just host the script in st2-packages repo and in documentation say wget ssh_script_loc | sudo sh

**Comment by armab** [comment]
Why we can't create it on fresh/first install and make it idempotent? It always worked well, even for `st2_deploy.sh`. Don't see any possible problem here, just good testing from different scenarios.

We can do this, absolutely.
At least SSH keys gen for sure and will see about other things.

**Comment by dennybaa** [comment]
@armab . hold on with this. we discussed it with @lakshmi-kannan and decided not to package it so far...

**Comment by armab** [comment]
Further discussion with @dennybaa : https://stackstorm.slack.com/archives/packages/p1454088219001579

I think it's possible to automate/polish these steps and make them always working. So users will have less steps to do manually.
As discussed, we won't do this right now. But I'm OK to return to this issue later.

**Comment by dzimine** [comment]
Decided to make it a work of user / or installer script, not the packages.

Creating a default user and adding it to SUDO is ok IMO.
