### ISSUE TITLE
Use built-in services in CI

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#13]
*Low priority*

CircleCI has built-in RabbitMQ, Mongo and PostgreSQL services already up and running.
Instead of downloading respective Docker images, we can use CI services to save some time (2-3 mins).

Since docker-compose supports different configs, depending on environment, this looks like good approach which won't break existing beauty.
http://docs.docker.com/compose/extends/#multiple-compose-files

So for local env and CI env there will be a bit different configs (with and without linked services).

**Comment by dennybaa** [comment]
Yeap. Btw we already using multiple compose files.

**Comment by dennybaa** [comment]
implemented in #17

**Comment by armab** [comment]
:+1:
