### ISSUE TITLE
Custom descriptions for packages in Bintray

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#137]
Currently we set "templated" metadata for all Bintray packages, so they all have same descriptions (even mistral), see [template file](https://github.com/StackStorm/st2-packages/blob/master/.bintray_package).

Extend [`bintray.sh`](https://github.com/StackStorm/st2-packages/blob/master/.circle/bintray.sh) so we could use custom metdata file/description for each package.

At the same time, we should double verify and provide real descriptions in all `deb`/`rpm` specs, not just: 
> Description: Mistral workflow service
insert long description, indented with spaces
Homepage:
insert the upstream URL, if relevant

here:  https://github.com/StackStorm/st2-packages/blob/51bd587112898dc9ea0ffbeca458d2d25287d659/packages/mistral/debian/control#L15-L16

---

Also keep in mind, we can't edit packages descriptions manually via Bintray WebUI, because of @enykeev :smiling_imp:  changes, see: 
https://github.com/StackStorm/st2-packages/pull/69#discussion_r49614908
https://github.com/StackStorm/st2-packages/pull/69#issuecomment-171540109

**Comment by enykeev** [comment]
Keep in mind that if we decide to switch to packagecloud, it has no additional meta for packages. If it's not a priority, better wait it out a little bit.

**Comment by armab** [comment]
We got some "rays of anger" from @dzimine yesterday that package descriptions are not actual, for example for `mistral`.

Also from yesterday meeting packages within Bintray will be released to public, at least for first release.

**Comment by armab** [comment]
Not needed anymore, since migration to PackageCloud:
https://github.com/StackStorm/st2-packages/issues/130
