### ISSUE TITLE
Untie `mistral-api` from `mistral` service

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#139]
`service mistral start/stop` currently controls both `mistral-server` and `mistral-api` as child services.
https://github.com/StackStorm/st2-packages/blob/master/packages/mistral/debian/mistral.upstart#L14
https://github.com/StackStorm/st2-packages/blob/master/packages/mistral/debian/mistral.upstart#L17

It was a good intent behind this and more simplicity, but it breaks scaling story, when API could live on different machine.

See for more info: https://github.com/StackStorm/st2/commit/6910a2106577af18810590a1ffdb85f5bb2dd227#commitcomment-15837593 @dzimine explanation in `st2ctl` PR.

---

Implementing this will also fix: https://github.com/StackStorm/st2-packages/issues/121

**Comment by dennybaa** [comment]
@armab if you don't mind to take it.
mistral wrapper service supports this mode https://github.com/StackStorm/st2-packages/blob/master/packages/mistral/debian/mistral.upstart#L11.

FYI they are coupled only in sysv (debian/el6) https://github.com/StackStorm/st2-packages/blob/master/packages/mistral/debian/mistral-server.init#L49. If you want to remove this restriction you should make sure that all env is passed.

Anyway each of mistral-api and mistral-server services MUST rely on COMPONENTS environment variable. unset means "api,engine,executor". However if set for ex. to `engine,executor` and you control mistral-api directly it should do no-op (i.e. fail).

**Comment by dennybaa** [comment]
resolved in #226
