### ISSUE TITLE
Cache pip between builds

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#14]
*One of future non-priority optimizations*

Pip downloads are pretty time-consuming, especially when there are big amount of packages.
Since we discovered that pip has lock problems and can't be parallelized during the concurrent package builds, one of possible options to improve the #7 speed among #11 and #13 is to cache pip downloads everywhere where it's possible to do by.

Share `~/.cache/pip` between running Docker containers (build containers/test containers),
so hopefully we won't download same packages every time again and again.

**Comment by dennybaa** [comment]
- Cache from build to build could be possible to save maybe on self-hosted CI.
- Share pip cache between parallel distro builds is not possible because pip is not thread safe.

None of the things are viable options for us right.

**Comment by armab** [comment]
> Cache from build to build could be possible to save maybe on self-hosted CI.

**Comment by dennybaa** [comment]
kk. leave it open for now.

**Comment by dennybaa** [comment]
implemented in #17

**Comment by dennybaa** [comment]
removing, follow #23
