### ISSUE TITLE
Vagrantfile

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#146]
> Low priority
> Part of the task when people need more docs, transparency and `1 click` simplicity

Include in `st2-packages` Vagrantfile which would allow us to build packages for respective distro and install/test packages in isolated environment (normal Vagrant VM, instead of Docker container).

Example is simple command `vagrant up el7` which does all the rest things: 
- setup `centos/7` VM
- installs Docker, Docker-compose
- runs `docker-compose` to produce el7 packages (replace `el7` with your distro)
- optionally installs packages on Vagrant machine (note why we launched `centos/7` machine for `el7` packages)
- optionally runs self-verification and so on stuff
- allow doing that for `el6 el7 trusty xenial`

As a result:
- you have Vagrant VM with fresh packages built from sources
- you still have an option to rely on `docker-compose` which runs inside Vagrant VM if you need testing under the Docker
- you can install on vagrant VM just produced packages
- everything is in one single place

`docker-compose` story is useful, but it's absolutely different. It installs packages in the Docker container, which is not always the case we need.
Sometimes (mostly) manual testing is needed under the normal VM.

---

Based on: 
- https://github.com/StackStorm/st2-packages/issues/144
- https://stackstorm.slack.com/files/phool/F0L890P6J/yabs_sh.sh
- https://github.com/enykeev/st2testground/
- https://github.com/StackStorm/st2docs/blob/master/docs/source/install/deb.rst

**Comment by dennybaa** [comment]
Yeah, that definitely would be neat.

**Comment by armab** [comment]
There is another repo: https://github.com/StackStorm/st2-packages-builder which only _partially_ does what's proposed in this Issue.

Eg. if you're working on `st2-packages` codebase there is no point to clone another `st2-packages-builder` repo. It's just waste of time.

Additionally, the idea here is to spin up `u14` Vagrant which produces same platform `u14` packages or `el6` vagrant should produce `el6` packages. This allows us to install just created packages without `up`-ing another Vagrant machine with needed distro.
