### ISSUE TITLE
st2actionrunner doesn't start in Jessie

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#156]
Reported here: https://github.com/StackStorm/discussions/issues/142#issuecomment-180805926
To verify if it's still an issue in latest package version.

Probably an issue related to permissions, since `st2actionrunner` is the only one that should start from root.

**Comment by dennybaa** [comment]
StackStorm/discussions#142 (comment) - was apparently could be caused by not full documentation available by that time.
Anyway I believe all actionrunner issues have been resolved with recent brushups. If it appears again let's get back to it... Meanwhile closing.
