### ISSUE TITLE
Bootstrap script needs to install curl 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2-packages#183]
I was doing some testing at it looks like distros make weird choices!

## CentOS 7 - wget not installed, curl is installed by default
```
[vagrant@centos7 ~]$ wget
-bash: wget: command not found
[vagrant@centos7 ~]$ curl
curl: try 'curl --help' or 'curl --manual' for more information
[vagrant@centos7 ~]$
```

## Ubuntu 14.04, wget is installed, curl is not installed by default
```
vagrant@u14:~$ wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
vagrant@u14:~$ curl
The program 'curl' is currently not installed. You can install it by typing:
sudo apt-get install curl
vagrant@u14:~$
```

So whatever the script is using, it should install the appropriate tool on the box.

**Comment by armab** [comment]
Responded in https://github.com/lakshmi-kannan/st2-packages/commit/820e1f088b8282c87bdb5db9125626589f39614e#commitcomment-16370091

**Comment by armab** [comment]
@lakshmi-kannan Please don't forget to close the issues, or it will be like in JIRA :trollface:

**Comment by dennybaa** [comment]
@armab  ha ha, I should've told that it's to heavy to bring this in bootstrap script, we should avoid installing additional software. The proper thing will be to probe wget and curl and chose the tool which is present :trollface:

**Comment by armab** [comment]
@dennybaa I responded in https://github.com/lakshmi-kannan/st2-packages/commit/820e1f088b8282c87bdb5db9125626589f39614e#commitcomment-16370091 

> Seems you're using some minimal/custom Ubuntu Vagrant image?
Official Ubuntu Vagrant image is:
```
config.vm.box = 'ubuntu/trusty64'
```
and it has `curl` installed by default.
Official AWS Ubuntu image has `curl` installed by default too.
^^ Verified both

So this is really custom minimal image issue. I asked not to use them.

**Comment by dennybaa** [comment]
I think you didn't get the joke dude)

**Comment by armab** [comment]
And yeah, bootstrap scripts is sh**)
