### ISSUE TITLE
Bootstrap script for RHEL shouldn't use -x and do what ubuntu does

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2-packages#185]
It looks like there are 3 votes to not using -x. Make things consistent across bootstrap scripts. 

https://stackstorm.slack.com/archives/stackstorm/p1456509067003174

As per kami and I, we should find a way to catch exit codes and explicitly quit if needed.

**Comment by lakshmi-kannan** [comment]
Looks like -x is already fixed. https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-el7.sh#L3

**Comment by armab** [comment]
`set -x` sets debug mode, so you see command executed from the script
`set -e` is what you're talking about about about exit codes.

Also see: https://github.com/StackStorm/st2-packages/issues/184#issuecomment-189622376
