### ISSUE TITLE
Ubuntu bootstrap script should follow EL7 instructions.

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2-packages#186]
After looking at EL7 instructions, I think I'd rather make ubuntu follow the same steps. EL7 script resembles the docs closer than ubuntu.

**Comment by lakshmi-kannan** [comment]
Apparently, I can't read very well. Ubuntu script actually was closer to docs.
https://docs.stackstorm.com/install/deb.html

I am an idiot. First let me make all scripts consistently inconsistent with the docs and then fix as and when needed.

**Comment by armab** [comment]
* Ubuntu follows its doc: https://docs.stackstorm.com/install/deb.html
* EL7 follows its doc: https://gist.github.com/armab/2ab4d2ccc592db422439

Also see *why* I followed different logic for `el7` doc & script. [From notes in that gist:](https://gist.github.com/armab/2ab4d2ccc592db422439#file-1-notes-md) 

> Because st2mistral requires more steps, st2 installation comes first to bring "fast win" feeling to user, when st2 could be installed in really 2 simple steps.

^^ I think that's more user-friendly.

**Comment by armab** [comment]
Resolved via https://github.com/StackStorm/st2-packages/issues/188
