### ISSUE TITLE
Docker Containers Caching in CircleCI?

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#22]
The pull stage in CircleCI when Docker containers dependencies are downloaded takes up to `2 mins` (usually 1.5).

Workaround to cache Docker Containers for CircleCI described here:
https://circleci.com/docs/docker#caching-docker-layers
https://circleci.com/docs/docker#some-known-caching-issues

Looks like dirty hack, probably requires crazy debugging to make it working for `docker-compose`.

**Comment by dennybaa** [comment]
Yeap, thanks. At the moment I'm not sure about the desired effect, since it's unclear how long it takes to freeze container and save/restore as cache via network. Definitely it requires some testing...
You might give a shot to it)
