### ISSUE TITLE
Following server reboot /run/mistral/ is missing and Mistral does not start

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2-packages#254]
Turns out the /run/mistral directory is created during package installation, however it's a tmpfs filesystem on Ubuntu:

```bash
tmpfs on /run type tmpfs (rw,noexec,nosuid,size=10%,mode=0755)
```

This means following a server reboot Mistral will not start, by the looks of things the init.d script should check if it exists and create it....

**Comment by jjm** [comment]
I'll do a PR to correct this after the AHH, the init.d scripts just need to check it exits on start of the two services and mkdir & chmod on start if missing.

**Comment by armab** [comment]
Yeah, not only `mistral`, but also `st2` services affected of this bug.

Regression starting with these PRs:  
* [st2](https://github.com/StackStorm/st2-packages/pull/215/files)
* [st2mistral](https://github.com/StackStorm/st2-packages/pull/226/files)

@dennybaa FYI we avoided approach of creating `/var/run/some_dir` when added `ginicorn` for `st2api` and `st2auth` because of these ^^ reasons (it's wiped after every reboot).

Thanks @jjm!

**Comment by jjm** [comment]
No worries,

Would you prefer this being a function somewhere and a call added to all the init.d scripts? Happy to change it to that later on....

**Comment by armab** [comment]
@jjm yeah, function would be cool to avoid code duplication :+1:

**Comment by jjm** [comment]
Indeed the PID files of ST2 are missing too, but it does not seem to prevent the services starting.

Given the discussion on PR #255 and it being a single line creating a function seems a little excessive....

**Comment by jjm** [comment]
By the looks of things all of the following are also missing, most likely due to lack of permissions. 

```bash
st2.st2actionrunner-worker.init:PIDFILE=/var/run/$NAME-${WORKERID}.pid
st2.st2exporter.init:PIDFILE=/var/run/$NAME.pid
st2.st2garbagecollector.init:PIDFILE=/var/run/$NAME.pid
st2.st2notifier.init:PIDFILE=/var/run/$NAME.pid
st2.st2resultstracker.init:PIDFILE=/var/run/$NAME.pid
st2.st2rulesengine.init:PIDFILE=/var/run/$NAME.pid
st2.st2sensorcontainer.init:PIDFILE=/var/run/$NAME.pid
```

I'll move these too into an st2 directory too. Hopefully only the iniit scripts will need changed and the files are not referenced else where...

**Comment by dennybaa** [comment]
@jjm what do you mean? On some particular platform they are not even created, kinda ubuntu.
Further on other debian platforms which are **NOT** upsturt, 
``` start-stop-daemon --start --quiet --chuid $RUNAS_USER:$RUNAS_GROUP --umask $UMASK --background --make-pidfile --pidfile $PIDFILE \
     --exec $DAEMON -- $DAEMON_ARGS \   || return 2``` takes care of it. So let's please clarify, what platforms are affect with the above.

**Comment by jjm** [comment]
I'm using Ubuntu 14.04, so that's my main reference. On our ST2 staging server I get the following:

```bash
$ ls -l /var/run/st2*
ls: cannot access /var/run/st2*: No such file or directory
```

So it would seem all PIDFILEs are not being created.

**Comment by dennybaa** [comment]
that's totally ok since ubuntu uses upstart and those pid files are not required to be created. upstart handles pid tracking of started daemons.

**Comment by jjm** [comment]
Cool, I'm also done sorting the PID files for the debian iniit scripts should be push'ed to the PR in the next 10 mins or so.

**Comment by dennybaa** [comment]
@jjm sounds great! just inject those missing `install` s:)

**Comment by jjm** [comment]
That' the update pushed, hopefully the CI will be ok this time :8ball: !

**Comment by jjm** [comment]
Cool :+1:

**Comment by armab** [comment]
Also,
thanks to your report @jjm we with @dennybaa found the root cause why you got mistral `pid` files created under `ubuntu trusty` (which shouldn't be created under this distro): 
https://github.com/StackStorm/st2-packages/issues/257

**Comment by jjm** [comment]
Thanks @armab, `upstart` is new to me and not really had a run in with it yet.
