### ISSUE TITLE
Ubuntu repo setup script should install GPG keys into /etc/trusted.gpg.d instead of globally

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2-packages#282]
So I keep running into this issue. Everytime I try to sudo apt-get update after installing StackStorm with packages on Ubuntu, I'll get errors like this:

```
W: GPG error: https://packagecloud.io trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37BBEE3F7AD95B3F
```

Just learned from our sysadmin that our trusted GPG keys are controlled via our config management system and that this is common in enterprise environments. When the StackStorm setup scripts does a `curl <keys_url> | apt-key add`, the keys are being adding to `/etc/trusted.gpg`, the global keyring. So the keys are lost after config mgmt runs.

We ended up adding the GPG keys to `/etc/trusted.gpg.d/` directory instead. This works much like adding the sources to `/etc/sources.list.d` to prevent them from getting clobbered.

PS - Sometimes I also get errors like this due to invalid cache. This may or may not be related to previous updates which failed due to GPG issues.

```
Ign https://packagecloud.io trusty InRelease
Get:1 https://packagecloud.io trusty InRelease
100% [Packages 42.3 MB] [1 InRelease gpgv 355 B]Splitting up /var/lib/apt/lists/partial/packagecloudErr https://packagecloud.io trusty InRelease    y_InRelease into data and signature failed

Ign https://packagecloud.io trusty InRelease

<snip>

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io trusty InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)
```

Clearing out the cache by rm'ing the files in `/var/lib/apt/lists/partial/packagecloud` fixed this for me.

**Comment by codyaray** [comment]
Looks like you could just create a new StackStorm keyring. This would just mean updating the setup script to change `apt-key add -` to `apt-key --keyring StackStorm.gpg add -`. 

http://manpages.ubuntu.com/manpages/wily/man8/apt-key.8.html

**Comment by codyaray** [comment]
A bit more context, the `apt-key add --keyring` line belongs in [script.deb.sh](https://packagecloud.io/install/repositories/StackStorm/stable/script.deb.sh), which I believe is managed by PackageCloud.io, so you'll need to work with them to make this change.

Otherwise of course I would have just opened a PR for such a small change. 👯

**Comment by lakshmi-kannan** [comment]
@codyaray Spoke with the packagecloud guys about this. They do have chef recipes and puppet modules to pull down the keys and write them to separate keyring. Do you think you can port the stackstorm installation to the config mgmt tool of your choice? Maybe that'd solve the problem for you?

Here is the conversation I had with a packagecloud engineer for more context - https://gist.github.com/lakshmi-kannan/c4006d46be10d3e9992f18664411c8ef

**Comment by codyaray** [comment]
@lakshmi-kannan Yeah, I was actually working on this a bit this morning -- building on the new ansible-st2 repo. It already had the basic key/stable sources present. I'm probably going to be sending a PR with the enterprise-specific stuff (conditional on the user providing a token).

**Comment by codyaray** [comment]
Still think that they should store in the keyring on OS where its supported (they're already doing OS detection). But depending on the number of OS's they require manual testing/verification on, I can see how this would be a pain.

**Comment by lakshmi-kannan** [comment]
As per offline convo with codyaray, closing this issue as there is no action item from st2 side.
