### ISSUE TITLE
Please build packages for Ubuntu 16.04 (Xenial)

### ISSUE THREAD

**Issue by darabos** [StackStorm/st2-packages#296]
I tried running https://raw.githubusercontent.com/StackStorm/st2-packages/master/scripts/st2bootstrap-deb.sh in the `ubuntu:16.04` Docker image. It appears to work fine until it tries to `apt-get install st2` which ends with:

```
E: Unable to locate package st2
```

It's the same when I follow the instructions at https://docs.stackstorm.com/install/deb.html#minimal-installation on a 16.04 system. `script.deb.sh` says `Detected operating system as Ubuntu/xenial.` and happily installs the repository for it, but the repo is empty.

Works fine on 14.04. (At least the package installation does. I'm just trying to give it a try, but couldn't get it up yet. I for one wish you'd standardized on Docker images instead of system packages.) Thanks!

**Comment by Kami** [comment]
Thanks for the suggestion.

We indeed only support 14.04 right now, but we do plan to also support 16.04 in the near future. It will require a bit more work though since Python 2.7 is not shipped by default anymore, etc.

**Comment by evguenig** [comment]
Workaround is to install st2 for ubuntu 14.04 on 16.04 xenial:
update file 
    /etc/apt/sources.list.d/StackStorm_stable.list

    to have
    deb https://packagecloud.io/StackStorm/stable/ubuntu/ trusty main
    deb-src https://packagecloud.io/StackStorm/stable/ubuntu/ trusty main
and then:
    sudo apt-get update

**Comment by triple-it** [comment]
We could of course check for the OS version in the st2bootstrap-deb.sh, and with 16.04 LTS at least give a warning? Would probably spare a lot of first experience head-ache with stackstorm, which is what we want, right? :-)

**Comment by armab** [comment]
@triple-it Sorry for that, the warning was there yesterday.

We just preparing to release `Ubuntu Xenial` packages these days and removed warnings to test everything end-to-end with our staging packages.

**Comment by lakshmi-kannan** [comment]
@darabos Sorry, it took a while but we are shipping xenial support this week as part of 2.1 release.

**Comment by armab** [comment]
Done in `v2.1` https://stackstorm.com/2016/12/06/2-1-new-pack-management/

**Comment by guptasakshi01** [comment]
Getting Below Error :
E: Unable to locate package st2
E: Unable to locate package st2mistral

Operating System : Ubuntu 14.04.5 LTS

**Comment by LindsayHill** [comment]
@guptasakshi01 not sure why you're posting on this issue? This issue was from 3 years ago. At the time we did not ship packages for Ubuntu 16.

Looks like you need to add the repositories to your system. Follow the install instructions at docs.stackstorm.com/install/index.html

**Comment by guptasakshi01** [comment]
Yeah I should have created new
Sorry for commenting on old post

I have followed the installation guide even after setting up repository I am getting this error.

**Comment by LindsayHill** [comment]
Make sure that this step completed successfully https://docs.stackstorm.com/install/deb.html#setup-repositories. Read the output, check for errors.

Check that you now have "https://packagecloud.io/StackStorm/stable/ubuntu/" as a repo on your system.

Run `apt-get update` and read all the messages on screen to check if it updated.
