### ISSUE TITLE
st2mistral package has no description

### ISSUE THREAD

**Issue by jvrplmlmn** [StackStorm/st2-packages#337]
While testing some changes for the `stackstorm-chef` cookbook, I noticed that on CentOS 7.2 the `st2mistral` package has no description:

```
vagrant@default-centos-72 ~]$ sudo yum info st2mistral
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.eu.oneandone.net
 * epel: nl.mirror.babylon.network
 * extras: mirror.eu.oneandone.net
 * updates: mirror.eu.oneandone.net
Available Packages
Name        : st2mistral
Arch        : x86_64
Version     : 2.0.0
Release     : 1
Size        : 27 M
Repo        : StackStorm_stable/x86_64
Summary     : Mistral workflow service
URL         : https://github.com/StackStorm/mistral
License     : Apache
Description :   <insert long description, indented with spaces>

[vagrant@default-centos-72 ~]$
```

It happens for RPMs:
https://github.com/StackStorm/st2-packages/blob/98e484303383f668e321bb43e6d14147400f5a61/packages/st2mistral/rpm/st2mistral.spec#L23-L24

and for DEBs:

https://github.com/StackStorm/st2-packages/blob/98e484303383f668e321bb43e6d14147400f5a61/packages/st2mistral/debian/control#L15-L16

**Comment by armab** [comment]
Good catch! :+1: 

Yeah, it was forgotten during packaging development, with shameful excuse like :smiley 
> Let's focus on development first, we don't have time to write the docs

Same for `st2web`:
  * https://github.com/StackStorm/st2web/blob/28441719787d6f9976fd534101b0d66409096687/debian/control
  * https://github.com/StackStorm/st2web/blob/28441719787d6f9976fd534101b0d66409096687/rpm/st2web.spec

**Comment by armab** [comment]
@enykeev Motivated to add some nice looking descriptions for `st2web`?
