### ISSUE TITLE
st2-bootstrap scripts should check sufficient disk space for MongoDB

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2-packages#341]
MongoDB pre-allocates a good chunk of disk space when starting. The bootstrap scripts should check that sufficient disk space is available before proceeding.

If insufficient space is available, the script should exit with an error message.

**Comment by armab** [comment]
Oh, we've been there: https://github.com/StackStorm/st2/blob/1df8f4cdd4fc4e3bd1eac79732d1b3aac1be4745/tools/st2_deploy.sh#L122-L129

This issue actually raises more important problem.

Things like this and that [#340: st2-bootstrap scripts should check listening ports](https://github.com/StackStorm/st2-packages/issues/340) will make existing bash bootstrap scripts kind of big godmode monsters again.

From what I remember, the original intent of bootstrap scripts is just to codify installation instructions, without handling corner cases.
@lakshmi-kannan what's the strategy now?

**Comment by LindsayHill** [comment]
My strategy right now is "avoid wasting support channel time, by catching problems early on"

**Comment by armab** [comment]
Yeah @LindsayHill I understand you and we all been there already.

I think adding more complexity to bootstrap bash scripts is a dead end. It's not the tool to handle these problems properly.
It's about investigating for users mongo installations, connection problems, postgres, nginx, firewall babysitting, disk space, ports, custom distros and all those permutations.

Let's not step on the same rake again.

* This approach of bash-monstrosity will bite #support more in a long-term, as it did before
* You can't predict everything with that bash-ery, there always will be another new non-catched problem
* With every new condition added to bootstrap script It will be harder to maintain it in a long term with 1.2K+ lines of code
* As a result we'll reach again and again that state when bash script finished successfully, but st2 wasn't installed
* bash just doesn't provide good enough error reporting & handling and acceptance testing

The suggestion is to define clearly recommendations "what is used for what" to avoid ^^ mentioned before pain as much as possible: 

1.) Bootstrap scripts are just to codify installation steps with no additional corner-case logic
2.) State clearly that for production use it's users responsibility to install st2 with configuration management tools (or manually) and handle all dependent services like databases, MQ, firewalls, and so on. If there is a problem - let they contribute to these repos.

Maybe even removing copy-paste `curl|bash` boostrap script from the installation docs will help people to think more, rather then turn off their brains.

**Comment by armab** [comment]
On related note, I remember there were even discussions to ship pre-built artifacts like: 
* virtualbox/vagrant
* vmware
* docker
* etc

Which will bring working st2 state and also useful for "private network".

**Comment by LindsayHill** [comment]
> Maybe even removing copy-paste curl|bash bootstrap script from the installation docs will help people to think more, rather than turn off their brains.

Not an option. Too many manual steps required for installation. Makes it far too high a barrier to entry for the casual user.

**Comment by armab** [comment]
Implemented in https://github.com/StackStorm/st2-packages/issues/387
