### ISSUE TITLE
Build Environment, docker images are outdated

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#343]
> Related to fast fix: https://github.com/StackStorm/st2-packages/pull/342

Originally packages are built in Docker environment, eg pre-bundled images for different OSes, located in https://hub.docker.com/r/stackstorm/packagingenv/tags/

These images need an update from time to time, since OS become obsolete/outdated/vulnerable.
Eg. rebuild Docker images, upgrade, deploy to Docker hub.

**Comment by enykeev** [comment]
Quay is supposed to build new images for us on every change to git tags. Please confirm and close the issue.

**Comment by armab** [comment]
Nice :+1: 

But more visibility would be nice.
Build happens on every git tag change in which repo? Where are links to Quay? How to know if error happens during the build? Documentation or maybe just badge to the index.

**Comment by armab** [comment]
Implemented in https://github.com/StackStorm/st2-dockerfiles/issues/40
