### ISSUE TITLE
st2exporter is abandoned

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#367]
_Suddenly_ some interesting findings about `st2exporter`: 

* There is `[exporter]` logging entry in [`st2.conf`](https://github.com/StackStorm/st2/blob/5efee113f98ca3ad412b370c9f40e4607c4b8f47/conf/st2.package.conf#L31-L32)
* But `/etc/st2/logging.exporter.conf` is not shipped and missing
* `/opt/stackstorm/st2/bin/st2exporter` couldn't be ran because there is no logging conf file
* There are prepared service/init files for `deb` and `rpm` in `st2-packages` repository
* But they [aren't shipped](https://github.com/StackStorm/st2-packages/blob/master/packages/st2/rpm/st2.spec#L31-L63)
* `Ubuntu14.04` service is missing
* `CentOS7` service is missing
* There is no entry in `st2ctl` services for `st2exporter`

So @Kami @lakshmi-kannan What is that `st2exporter` thing after all?
Sync-up is needed here to clean-up unneeded config entries or maybe resurrect that forgotten service.

**Comment by cognifloyd** [comment]
These should clean this up:
https://github.com/StackStorm/st2-packages/pull/723
https://github.com/StackStorm/st2/issues/5295
