### ISSUE TITLE
[INFO] Moar Parallel Docker Operations

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#38]
Opening this issue for informational purposes (not to forget).

2 docker-related tickets to track, that would be useful for us in future to further improve [CI pipeline](https://circleci.com/gh/StackStorm/st2-packages) (speed improvements where possible):
- [Concurrent "docker build" takes longer than sequential builds](https://github.com/docker/compose/issues/1652)
- [Epic: Improve performance by running operations in parallel](https://github.com/docker/docker/issues/9656)

What we alredy do:
- Push images to Docker Hub in parallel

**Comment by dennybaa** [comment]
@armab, What docker operations do you suggest to parallelize?

**Comment by armab** [comment]
I'll wait for native support (see links above) for `build` and `pull`.

**Comment by dennybaa** [comment]
@armab let's close it) too many non-viable things, messing up the issue board))

**Comment by armab** [comment]
It's just easier to keep it on radar this way (aka TODO).

**Comment by armab** [comment]
With https://github.com/docker/compose/pull/4428 pull can work in parallel:
```
docker-compose pull --parallel
```
should be available in docker-compose `v1.12`

**Comment by dmitryplatonov** [comment]
Parallel push would be very nice.
