### ISSUE TITLE
[EL7][st2bootstrap-el7.sh] nodejs from epel always take precedence

### ISSUE THREAD

**Issue by shusugmt** [StackStorm/st2-packages#437]
epel-release will be installed at here:
https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-el7.sh#L261

then, nodejs 4 repository will be configured at here:
https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-el7.sh#L554-L555

but it will never be used because `nodejs` package from epel-release is newer so while installing st2chatops, dependent installed `nodejs` is not the one from `rpm.nodesource.com`

Maybe this is just a bug of the script?

**Comment by armab** [comment]
Thanks for the report, it's a good catch :+1: 

So it looks like [`EPEL`](https://dl.fedoraproject.org/pub/epel/7/x86_64/n/) has `nodejs 6.9` while `Nodesource 4` has `nodejs 4.8`.
Yeah, this is a time ticking bomb when EPEL could ship some newer version which will break things for us.

@s2ugimot BTW any problem you hit with `nodejs 6.9`?

**Comment by s2ugimot** [comment]
@armab 

> BTW any problem you hit with nodejs 6.9?

Wish I could tell, but I'm just not using st2chatops at my installation yet...

**Comment by armab** [comment]
@enykeev @emedvedev Do you know if there is a node version which could break the things for us?
Also should we/is it a good reason to update our bootstrap scripts to newer https://rpm.nodesource.com/setup_6.x from https://rpm.nodesource.com/setup_4.x?

Additionally, for safety we can add max allowed node version in packaging spec:
- [`.rpm`](https://github.com/StackStorm/st2chatops/blob/master/rpm/st2chatops.spec#L9)
- [`.deb`](https://github.com/StackStorm/st2chatops/blob/master/debian/control#L14)

**Comment by armab** [comment]
Since we switched to nodejs6 by default for `st2chatops`, this is fixed now.
See https://github.com/StackStorm/st2chatops/pull/78 and https://github.com/StackStorm/st2chatops/issues/83 where we rely on specific major node version via packaging dependencies.
