### ISSUE TITLE
Docker-compose fails build

### ISSUE THREAD

**Issue by PeteClapham** [StackStorm/st2-packages#441]
Error is:

pete@box:~/docker/st2-packages$ docker-compose kill; docker-compose rm -f; docker-compose run --rm wheezy
Going to remove st2packages_postgres_1
Removing st2packages_postgres_1 ... done
Creating st2packages_postgres_1
ERROR: driver failed programming external connectivity on endpoint st2packages_postgres_1 (51afec4805ab54894b121674265f31a5a930c067b21e6e782bec7f869a029421): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

Host OS
pete@box:~/docker/st2-packages$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

Docker versions are:
pete@box:~/docker/st2-packages$ dpkg -l |grep docker
ii  docker-compose                              1.5.2-1                                       all          Punctual, lightweight development environments using Docker
ii  docker.io                                   1.12.6-0ubuntu1~16.04.1                       amd64        Linux container runtime
ii  python-docker                               1.8.0-0ubuntu1                                all          Python wrapper to access docker.io's control socket
ii  python-dockerpty                            0.3.4-1build1                                 all          Pseudo-tty handler for docker Python client (Python 2.x)

Thank you for any thoughts
Pete

**Comment by armab** [comment]
From the following error: 
> Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

looks like `5432` port is already used by some other process (postgresql?).

Check what's listening on `5432`:
```
sudo netstat -tulpn | grep 5432
```

**Comment by armab** [comment]
Alternative approach is to use Vagrant to isolate everything in VM.
See: https://github.com/StackStorm/st2-packages#vagrant-based-build-and-test how to use it
```
vagrant up trusty
```

This will install Docker inside the Virtual Machine and build `.deb` packages in that environment.

**Comment by armab** [comment]
Closing.

Please provide more info, if you're still experiencing this issue.
