### ISSUE TITLE
Multiple bugs in 'st2mistral' package under Ubuntu16 (systemd)

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#455]
During the ops-infra work, random bugs found under `Ubuntu16` (systemd) for `st2mistral` package:

- [ ] `systemd` unit files are missing for [`deb`](https://github.com/StackStorm/st2-packages/tree/master/packages/st2mistral/debian) packages (!)
- [ ] After _uninstalling_ `st2mistral` package:
  - [ ] mistral services remain in the running state
  - [ ] `service mistral restart` is executed and reports some status, even without a package installed
  - [ ]  `SysVInit` scripts were not deleted
  - [ ] it's not possible to stop `mistral-server` normally, its state remains "active"

It looks like we didn't implemented systemd and never tested it properly under Ubuntu16 :man_facepalming:  :fist_oncoming:

**Comment by armab** [comment]
Also just noticed, `sudo service mistral-api stop` never stops the service (in normal conditions, having `st2mistral` package installed).

**Comment by andrew-regan** [comment]
Seeing a similar issue on CentOS 7. I noticed that `mistral-server` was not responding to `systemctl stop mistral` and systemd would eventually forcefully terminate the process. quick code inspection all I could find was a `KeyboardInterrupt` handler in the code so adding `KillSignal=SIGINT` to the mistral-server.service file looks to have done the trick.
