### ISSUE TITLE
st2mistral package needs logrotate configuration file

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2-packages#468]
The st2mistral package should ship with a logrotate configuration file, similar to https://github.com/StackStorm/st2/blob/master/conf/logrotate.conf

Otherwise the Mistral logs get out of hand, e.g:

```
brocade@BWC:/var/log/mistral$ du -hs *
8.0K    mistral-api.log
457M    mistral-server.log
brocade@BWC:/var/log/mistral$
```

This should have the same rotation policy as the st2 logrotate configuration. 

Important:
- file should not get deleted on RPM upgrade
- Ensure mistral gracefully handles re-opening log files.

**Comment by JohnWelborn** [comment]
/etc/mistral/logging.conf could be modified as:
https://github.com/openstack/mistral/blob/master/etc/logging.conf.sample.rotating
