### ISSUE TITLE
Fix or skip action registration during Mistral DB init

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2-packages#487]
https://github.com/StackStorm/st2-packages/pull/486 suppresses expected errors in the bootstrap script when populating the Mistral database (seemed to be new behavior as of 2.4). This obviously doesn't fix the underlying problem, so we may want to spend some time trying to figure out why these errors are occurring in the first place.

I personally am 👍 to just skipping all these actions in the first place, they're not relevant to a mistral+st2 installation. https://github.com/openstack/mistral/blob/master/mistral/actions/openstack/mapping.json seems to be where the current mapping is done - maybe use our own file?

# TODO

- [ ] Skip the actions
- [ ] Revert https://github.com/StackStorm/st2-packages/pull/486

**Comment by armab** [comment]
@Mierdin Same file in our fork: https://github.com/StackStorm/mistral/blob/master/mistral/actions/openstack/mapping.json
