### ISSUE TITLE
Modify bootstrap script to specify driver for Mistral/Postgresql

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2-packages#490]
In our bootstrap scripts, we configure the Postgresql connection in `/etc/mistral/mistral.conf` with this:

```
sudo crudini --set /etc/mistral/mistral.conf database connection "postgresql://mistral:${ST2_POSTGRESQL_PASSWORD}@127.0.0.1/mistral"
```

This results in these warnings at startup in the logs, and on-screen during installation:

```
2017-08-22 03:00:34.783 13095 WARNING oslo_db.sqlalchemy.engines [-] URL postgresql://mistral:***@127.0.0.1/mistral does not contain a '+drivername' portion, and will make use of a default driver.  A full dbname+drivername:// protocol is recommended.
```

We should specify the driver

The Mistral docs are not helpful here (their example is the legacy style), but I think this is what it should look like:

```
sudo crudini --set /etc/mistral/mistral.conf database connection "postgresql+psycopg2://mistral:${ST2_POSTGRESQL_PASSWORD}@127.0.0.1/mistral"```

**Comment by armab** [comment]
:+1: 
We have `mistral.conf` in place https://github.com/StackStorm/st2-packages/blob/master/packages/st2mistral/conf/mistral.conf#L237 so it's possible to modify defaults there.
