### ISSUE TITLE
Write install logs to file as well as stdout

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2-packages#499]
When the installation scripts run, they produce large amounts of output to screen. This can be useful information for debugging purposes.

Unfortunately it is only displayed in that session. Sometimes users window buffers don't contain enough info, or they are doing it via the VM console, making it difficult to capture. Or they log out of that session, and lose the content.

Then when we want to debug installation failures, we don't have the content.

During installation, we should write all output to a file, as well as to screen, e.g. using `tee` or similar.

This file should be stored somewhere sensible, perhaps in `/var/log/st2/install.log.<timestamp>`, or maybe `$HOME/st2.install.log.<timestamp>`

**Comment by warrenvw** [comment]
I'm 👍 for `/var/log/st2/install.log.<timestamp>`.

Does it make sense to include the output of commands run prior to installation that identify OS version and any other useful data. e.g. `uname -a`, `cat /etc/lsb-release` or `cat /etc/redhat-release` ..., `netstat -an`, `st2 --version`, ... ? These are always questions that support folks have to ask of people reporting issues.

**Comment by Kami** [comment]
+1.

As far as the file name goes - `st2install.<timestamp>.log` or similar. I believe it should have `.log` suffix so it's consistent with other log files (usually you do find *.log and not find *.log*).

And I agree on including other additional useful information. In a sense, this looks like "installer version" of `st2-submit-debug-info`. There we include OS version, Python version, installed packages, etc.
