### ISSUE TITLE
Info: TravisCI

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#5]
*Just for info here, thoughts about using TravisCI for building packages*

----

Build went well in TravisCI with 3 tasks running in parallel:
[![](http://i.imgur.com/Yiw1CGf.png)](https://travis-ci.org/armab/st2-packages/builds/86485467)

#### Example configuration
* [Example build page](https://travis-ci.org/armab/st2-packages/builds/86485467)
* [TravisCI configuration](https://github.com/armab/st2-packages/blob/travis-ci/.travis.yml)

#### Things I don't like
* It's pretty slow. Fastest is `debian` (15 min). But the overall build time is time of slowest task which is `centos7` (28 min 10 sec). Not reliable enough for CI tied with GitHub.
* TravisCI has no callback when **all** tasks completed successfully (we need to upload artifacts when everything went well), see https://github.com/travis-ci/travis-ci/issues/929. However there is 3rd party workaround `travis_after_all` https://github.com/dmakhno/travis_after_all , so it's doable somehow.
* Less likely we can tie it into `st2` repo, because [there are already existing unit/integration tests running in TravisCI for `st2`](https://travis-ci.org/StackStorm/st2)
  * Configuration will be mess if we merge package builds and unit/lint/integration tests into one thing in TravisCI
  * Not enough parallel slots (4 free for OSS projects: we already use 4 in `st2` and 3 parallel slots for packages here)
  * In GitHub Pull Request status it's better to separate logically different builds by using [different CI](http://i.imgur.com/2G1kZX0.png), so every CI can show its status ASAP.

----

Going to try CirlecCI now and dig into Drone docs later.

**Comment by dennybaa** [comment]
Thank you for the detailed review. Now we can keep travis in our view scope. Nice!)

The first - yeah unpredictable build time is bad, but I've seen it before with a dedicated cloud node, better to have a good cloud...)

The second yeah this sucks, so travis doesn't provide us a way to do the required action (publish packages somewhere) from the box.

Third, no no we don't want and need to tie up to our existing travis workflow. We rather want to untie and simplify the **"test on a git commit"** stage.
It's clear that we need another CI instance for the task of building packages, and it should be triggered via argument enabled hook, this is the best case. What I mean by an argument enabled hook is that a person can initiate a build say it: *build debian with arguments repo=st2-packages branch=master st2ver=0.15 st2rel=dev15*.

**Comment by armab** [comment]
There are 2 cool things about Travis I've found today also:

* [Uploading Artifacts to S3 via Travis CI](http://docs.travis-ci.com/user/uploading-artifacts/)
* [GitHub Releases Uploading via Travis CI](http://docs.travis-ci.com/user/deployment/releases/)

**Comment by dennybaa** [comment]
1. drone also has it..., but probably we won't need s3 feature at all. Since our plan to use bintray.com. 
2. yeah, nice +1

I've just had a short look into the second thing, and was surprised - `github_key` goes in the `travis.yml` so it's seems to be public. Can you clarify this moment?

**Comment by armab** [comment]
They most probably mean encrypted by Travis keys, see: http://docs.travis-ci.com/user/encryption-keys/ (same logic with keeping secrets encrypted, as you might have in any Configuration Management tool).

Also it's possible to set ENV variables in Travis UI.

**Comment by dennybaa** [comment]
@armab have a look https://github.com/drone/drone/tree/master/plugin/publish
wow, it seems quite extensive. And there's bintray plugin already available)

**Comment by armab** [comment]
Nice! Drone plugin directory is definitely something we should dig more later. The bad thing is that I can't find plugin dir in `0.4` branch (as you said parallel support starts from this version): https://github.com/drone/drone/tree/0.4.0

-----

Just found that Travis has built-in deploy to Bintray also: http://docs.travis-ci.com/user/deployment/bintray/

Here is another bash example via Bintray API (simple CURL POST): https://github.com/bintray/bintray-examples/tree/master/bash-example

Ok, at least I hope we won't have problems uploading to Bintray.

**Comment by armab** [comment]
Btw, nice page here: http://addons.drone.io/ :cake: 
We should have something nice looking like this for StackStorm packs/integrations.

**Comment by dennybaa** [comment]
yeap. bintray has its API, however less scripting is what we need. So it's nice that we've got already ready bintray integrations for travis and drone, so no need in wheel reinvention)

**Comment by dennybaa** [comment]
okay Travis is not our option, we've chosen Circle CI (details here #6), so closing it.
