### ISSUE TITLE
Installation script should handle non-standard HOME location

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2-packages#501]
The installation scripts assume that ~stanley is `/home/stanley`. 

Some environments use a different base path for home directories, e.g. `/export/home/$USER`. This causes problems with the installation script which assumes that ~stanley's SSH key is in `/home/stanley/.ssh`. This should be identified automatically.

**Comment by warrenvw** [comment]
In bash, we could use `eval echo "~$SYSUSER"`, where `$SYSUSER` is the StackStorm system user as defined in `/etc/st2/st2.conf` at `system_user/user`.
