### ISSUE TITLE
New Packages and st2ctl

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#51]
Core Action `st2 packs.restart_component` and `st2 packs` depends on `st2ctl` script, which doesn't exist in new packages system, because of new shiny init/upstrart startup scripts.

Not sure about current/future plans about `st2ctl`.
Or we should still ship `st2ctl`, or edit `st2` core actions:
* [`packs.load`](https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/load.yaml)
* [`packs.packs.restart_component`](https://github.com/StackStorm/st2/blob/master/contrib/packs/actions/restart_component.yaml)

And other occurencies: https://github.com/StackStorm/st2/search?p=1&q=st2ctl&utf8=%E2%9C%93

If edit `st2` actions, - then new release version should be shipped only with new Packages and startup scripts.

#### Reproduce: 
```sh
$ st2 run packs.restart_component servicename=st2auth
.
id: 567583ff73b55b33b955b0a4
status: failed
parameters:
  servicename: st2auth
result:
  failed: true
  return_code: 127
  stderr: 'bash: st2ctl: command not found'
  stdout: ''
  succeeded: false
```

**Comment by dennybaa** [comment]
I see, imo. If packages show themselfs well. I guess this is not viable duplication... Of course much cleaner approach is to let a user to invoke `systemctl restart st2auth` or `restart st2auth`.

**Comment by armab** [comment]
Double checked the [`st2ctl`](https://github.com/StackStorm/st2/blob/master/tools/st2ctl#L125).

Yeah, we should ship `st2ctl` and adopt it with new packages environment (+ backward compatibility).

**Comment by dennybaa** [comment]
@armab You think we can close it already?

**Comment by armab** [comment]
Hey @dennybaa I mentioned you here: https://github.com/StackStorm/st2-packages/pull/64#issuecomment-170687675
Take a look at code.

**Comment by armab** [comment]
Fixed by https://github.com/StackStorm/st2-packages/pull/64

New refactored `st2ctl` is now part of `st2common` package: https://github.com/StackStorm/st2/blob/master/st2common/bin/st2ctl
