### ISSUE TITLE
Move build to CircleCI 2.0

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#536]
We've moved to `CircleCI 2.0` for `StackStorm/st2` repository a long time ago.

Logically, packages build in `st2` and `st2-packages` repositories do the same thing.

The bigger difference is in mechanics: `st2-packages` is on `CircleCI 1.0`, while `st2` is on `CircleCI 2.0`. Considering that `v1.0` gradually abandoned, we see more and more diff in build reliability & results.

----

Move `st2-packages` to CircleCI 2.0, following the `st2` repo example:
https://github.com/StackStorm/st2/blob/master/circle.yml#L108-L248
As a bonus, switching to new CircleCI infra will bring faster build times.

**Comment by Kami** [comment]
Circle CI 1.0 will be EOL in August so some more motivation of us to move to 2.0 :)
