### ISSUE TITLE
Add Ubuntu 18.04 support

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#554]
Ubuntu `18.04` releasing `Ap 26, 2018`.
Per @LindsayHill, the plan for adding Ubuntu Bionic Beaver support is the following:

> Current thinking is along the lines of:
>- Add u18 support in 3-6 months
>- *drop* u14 support next April, when it goes end of LTS
>- Aim to add RHEL 8.x support when 8.1 ships
>- Drop RHEL 6.x at that time
>There is also related work going on with adding more Py3 support, but we don't have a firm date for dropping py2.7

Related https://github.com/StackStorm/puppet-st2/issues/213

**Comment by LindsayHill** [comment]
I think we should target u18 support for after 18.04.1 gets released - probably around July timeframe. Assuming we ship 2.8 around June, then target u18 support for the next ST2 version after that.

**Comment by LindsayHill** [comment]
MongoDB 4.0.x is the only release supported on Ubuntu 18.04. So we'll need to sort out https://github.com/StackStorm/st2/issues/4098 - and move to 4.0 - before we can add Ubuntu 18.04 support.

**Comment by armab** [comment]
Closed in https://github.com/StackStorm/st2-packages/pull/618
