### ISSUE TITLE
Info: CircleCI

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#6]
*Just for info here, thoughts about using CircleCI for building packages*

----

Same as Travis, it went well in CircleCI with built-in parallel support (3 tasks).
FYI for free (OSS projects) we have 4 isolated VMs running in parallel, - same as Travis.

[![](http://i.imgur.com/D1Rwz1L.png)](https://circleci.com/gh/armab/st2-packages/50)

#### Example configuration
* [Example build page](https://circleci.com/gh/armab/st2-packages/50)
* [circle.yml configuration](https://github.com/armab/st2-packages/blob/circle-ci/circle.yml)

#### Pros
* [powerful VMs, 32 CPUs](https://cloud.githubusercontent.com/assets/1533818/10668028/99b8771a-78da-11e5-8fee-f8a68060d9e9.gif)
* Has [`deployment`](https://github.com/armab/st2-packages/blob/circle-ci/circle.yml#L41) section which is triggered when **all** parallel tasks were finished successfully. That's what we need and what's hard to do in Travis.
* Has `debug ssh` mode
* Parallel nodes can run ssh commands on each other: `ssh node0` `ssh node1`
* Has `artifacts` section. You just copy created artifacts to `$CIRCLE_ARTIFACTS` directory and CircleCI makes them downloadable after the build. [See screenshot](http://i.imgur.com/pcWttxa.png). 
* Has option to trigger Parameterized Builds via API (see links below).

#### Cons
* [`circle.yml`](https://github.com/armab/st2-packages/blob/circle-ci/circle.yml) config is not so clear as [`travis.yml`](https://github.com/armab/st2-packages/blob/travis-ci/.travis.yml). Configuration was harder with some small issues/dirty hacks. But most probably we want to configure it once and forget about it.

#### Other Useful links
* [circle.yml configuration](https://circleci.com/docs/configuration)
* [CircleCI API](https://circleci.com/docs/api)
* [Trigger Parameterized Build via API](https://circleci.com/docs/parameterized-builds) - trigger a build via API and inject custom ENV variables. Also allows us to trigger one build from another. [EXAMPLE with nighty-builds](https://circleci.com/docs/nightly-builds)
* [Howto: Publish your binaries in Github with CircleCI](https://medium.com/@jgautheron/publish-your-golang-binaries-in-github-with-circleci-e0b64cb21bf8#.t267i6qbg)

#### Some Conclusions
* I can't say that CircleCI wih 32CPUs is slow, but build time is very near to what we have in Travis:
   * `~15min` - for `debian`
   * `~18min` - for `ubuntu`
   * `~26min` -  for `centos7`

Looks like we need some enhancements to further parallelize the builds. I've noticed that CircleCI 32 CPUs were not heavily used during the build. For the moment all packages `ST2_PACKAGES="st2common st2actions st2api st2auth st2client st2reactor st2exporter st2debug"` are building one-by-one. We should think about improvements here to better use all machine's horse-power.

------

So far it's better than Travis.
Going to try Drone now.

**Comment by dennybaa** [comment]
Splendid.
Yeah it's a nice point to make build of packages in parallel :+1: )

Try drone but not a cloud version but a hosted one, please.
What makes me suspicious so far is that build machines in cloud versions either of travis or whatever might be chosen dynamically. This can result in further speed reduction, since it might be needed to fetch docker images on each build...

**Comment by armab** [comment]
Moved discussion about the build time here:
https://github.com/dennybaa/st2-packages/issues/7

**Comment by dennybaa** [comment]
kk

**Comment by dennybaa** [comment]
Closing since it's our preferred way to go)
