### ISSUE TITLE
Bug in echo command on st2bootstrap-deb.sh

### ISSUE THREAD

**Issue by AshleyDumaine** [StackStorm/st2-packages#624]
* [x] Operating system: Ubuntu 16.04.6 LTS
  * [x] StackStorm version: st2 3.1.0, on Python 2.7.12

# Issue details
I'm trying to install Stackstorm with the one-line install command here, however it's failing: https://docs.stackstorm.com/install/index.html#ref-one-line-install

I noticed on line 500 (https://raw.githubusercontent.com/StackStorm/st2-packages/v3.1/scripts/st2bootstrap-deb.sh) there's a bad echo command:
```
  sudo sh -c 'echo "security:\n  authorization: enabled" >> /etc/mongod.conf'
```
This puts the \n (not an actual newline) into the mongodb config and makes it so mongodb can't start. Instead of `echo` this should probably be `printf` so the \n gets properly formatted.

**Comment by armab** [comment]
```sh
$ sudo sh -c 'echo "security:\n  authorization: enabled"'
security:
  authorization: enabled
```

What's your OS/environment?

**Comment by AshleyDumaine** [comment]
Very odd, though I do notice adding `-e` on the echo resolves it:
```
$ sudo sh -c 'echo "security:\n  authorization: enabled"'  
security:\n  authorization: enabled
$ sudo sh -c 'echo -e "security:\n  authorization: enabled"'
security:
  authorization: enabled
```

**Comment by armab** [comment]
I'm guessing the behavior depends on different versions used. Sounds like `-e` might work or not too (https://stackoverflow.com/questions/8467424/echo-newline-in-bash-prints-literal-n).

I'm good with your suggestion replacing it with `printf`:+1:
Mind creating a PR to fix this?

**Comment by AshleyDumaine** [comment]
Sounds good, will do!
