### ISSUE TITLE
[deb] st2reactor accidently doesn't depend on st2common

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#63]
I see there is a dependency [in Makefile](https://github.com/StackStorm/st2-packages/blob/78bc21938e70194252d5462c5e1f73445b449058/packages/st2reactor/Makefile#L46)
But `st2reactor` for some unknown reason doesn't depend on `st2common`.

#### Reproduce (Ubuntu14):

Add repo:
```sh
wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -
add-apt-repository 'deb https://dl.bintray.com/stackstorm/trusty_staging unstable main'
```

Install st2reactor
```sh
# apt-get install st2reactor

The following NEW packages will be installed:
  st2reactor
0 upgraded, 1 newly installed, 0 to remove and 34 not upgraded.
```

Only `st2reactor` is installed (no `st2common` dependency):
```sh
# ls -d /usr/share/python/st*
/usr/share/python/st2reactor
```

and
```sh
apt-cache showpkg st2reactor
```
shows no depdency.

----

Probably typo somewhere or something like that in https://github.com/StackStorm/st2-packages/tree/master/packages/st2reactor I don't see.

**Comment by dennybaa** [comment]
How that's weird awesome catch. I'll Google it  tomorrow.

**Comment by dennybaa** [comment]
BTW other packages okay?

**Comment by armab** [comment]
Yes

**Comment by dennybaa** [comment]
fixed https://github.com/StackStorm/st2-packages/commit/ea47e8b0913c470928a09d93d9dfd91ce9cf4bdd
