### ISSUE TITLE
packagingrunner failed at ppc linux - exec user process caused "exec format error"

### ISSUE THREAD

**Issue by dove-young** [StackStorm/st2-packages#648]
If you find an issue in packages, please file an issue and we'll have a look as soon as we can.
In order to expedite the process, it would be helpful to follow this checklist and provide
relevant information.

  * [x ] Operating system: `uname -a`, `./etc/lsb_release` or `cat /etc/redhat-release`
```
[root@ramtil1 st2-packages]# uname -a
Linux ramtil1.fyre.ibm.com 4.18.0-147.el8.ppc64le #1 SMP Thu Sep 26 15:44:34 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
[root@ramtil1 st2-packages]#
[root@ramtil1 st2-packages]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.1 (Ootpa)
[root@ramtil1 st2-packages]#
```
  * [ ] StackStorm version: `st2 --version`
  * [ ] Actual package versions of all packages (st2, st2web, st2chatops, st2mistral, nginx, mongo, rabbitmq-server, postrgresql; Enterprise: st2flow, st2-auth-ldap)
    DEB: apt-cache policy ${PACKAGE_NAME} will give you the version of package.
    RPM: yum info ${PACKAGE_NAME} will you give the version of package.
    Note the exact name of mongo, nginx, rabbitmq and postgres changes based on OS.
  * [ ] Contents of /etc/st2/st2.conf
  * [ ] Output of st2ctl status
  * [ ] Optional - Details about target box. E.g. vagrant box link or AWS AMI link.

#Issue details

I tried to run `quay.io/stackstorm/packagingrunner`  at RH Linux ppc.  It failed at execution. 

```
[root@ramtil1 st2-packages]# podman pull quay.io/stackstorm/packagingrunner
Trying to pull quay.io/stackstorm/packagingrunner...
Getting image source signatures
Copying blob 1211ffdf2fbb skipped: already exists
Copying blob a3ed95caeb02 skipped: already exists
Copying blob 292159885dfc skipped: already exists
Copying blob 065a8a8d2c50 skipped: already exists
Copying blob adcc39647161 skipped: already exists
Copying blob 38e75c9bc00a skipped: already exists
Copying blob dc94b9763167 skipped: already exists
Copying blob 949885f61170 skipped: already exists
Copying blob 9293c9f72d97 skipped: already exists
Copying blob b11f88577c81 skipped: already exists
Copying blob a3ed95caeb02 skipped: already exists
Copying blob a3ed95caeb02 skipped: already exists
Copying blob 1ada27c4caed skipped: already exists
Copying blob 23237bba0ac1 skipped: already exists
Copying blob a3ed95caeb02 skipped: already exists
Copying blob b0b3de6b132b skipped: already exists
Copying blob 9e02904d451f skipped: already exists
Copying blob 2aa0fc8fa5d3 skipped: already exists
Copying blob 13f1f110799a skipped: already exists
Copying config d075237b30 done
Writing manifest to image destination
Storing signatures
d075237b301fceb1f11aa7e8808d0802af3c9086743f9d1381b32826ec761778
[root@ramtil1 st2-packages]# podman run -it --rm --name st2packages_el8_run_1 quay.io/stackstorm/packagingrunner
standard_init_linux.go:211: exe
```

**Comment by armab** [comment]
Based on your `uname -a` you're running `pc64el`, while the packaging toolset is confirmed to be running under the `amd64` architecture and Docker images were built for the x86_64 arch.

I'd suggest to try on a different machine with compatible architecture as `pc64el` and `x86_64` are not binary-compatible.

**Comment by armab** [comment]
Closing as `pc64el` arch is not supported.
