### ISSUE TITLE
rabbitMQ version on EL8 hardcoded

### ISSUE THREAD

**Issue by amanda11** [StackStorm/st2-packages#694]
The EL8 installation of ST2 pulls rabbitMQ from the packagecloud rabbitmq repository. The latest version requires an erlang version that is greater than the version that is pulled from the EL8/EPEL repositories.

This was resolved for 3.4 by pinning the rabbitMQ version to the last version that used the older erlang in PR https://github.com/StackStorm/st2-packages/pull/693.

It would be desirable to be able to pick up bug-fixes, so if rabbitMQ is available in epel then take from there, or look to see if can fetch erlang version that is compatible with latest rabbitMQ.

**Comment by jamesdreid** [comment]
Ran into this issue on my most recent Centos upgrade and was able to correct it by removing the EPEL version included with Centos 8.1 and re-installing "Zero Dependency" version of erlang supplied by the RabbitMQ as outlined in:

https://github.com/rabbitmq/erlang-rpm

Not sure if it created other issues with the system, but it got my Lab ST2 install going again so it may be an option to use this package in the standalone install.

**Comment by amanda11** [comment]
> Ran into this issue on my most recent Centos upgrade and was able to correct it by removing the EPEL version included with Centos 8.1 and re-installing "Zero Dependency" version of erlang supplied by the RabbitMQ as outlined in:
> 
> https://github.com/rabbitmq/erlang-rpm
> 
> Not sure if it created other issues with the system, but it got my Lab ST2 install going again so it may be an option to use this package in the standalone install.

Thanks for feedback. Good to know that you haven’t had issues with the rabbitmq erlang - as that probably would be my preference..

**Comment by jamesdreid** [comment]
I have been on the "unstable" branch of ST2 since the 3.4 testing so it does not apply to stable/production/3.4, but I just completed the self tests successfully in my lab with the "rabbit_erlang" package installed.
