### ISSUE TITLE
CI for Mistral

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#82]
Currently we build and upload same `stable` mistral version on every push to `st2` and `st2-packages`, which is overkill. It's hardcoded here: https://github.com/StackStorm/st2-packages/blob/610a3064a05f7a03531a576aabd9b592c877eaaf/rake/build/environment.rb#L81-L85

We should build Mistral only when there was a change/release in https://github.com/stackstorm/mistral repository. Of course, CircleCI should be integrated with `mistral` repo, same as @enykeev did for `st2web`.

This will further speed up overall build time for `st2-packages` and `st2` repos, since we won't do unecessarry mistral builds every time.

**Comment by lakshmi-kannan** [comment]
+1 to this suggestion. I wonder how we would version mistral if we did this. Currently we branch mistral based on st2 versions.

**Comment by dennybaa** [comment]
+1 yep agreed let's tackle it as soon we get some free time.

**Comment by armab** [comment]
Also it started us biting here:
https://stackstorm.slack.com/archives/stackstorm/p1455567734000203
https://stackstorm.slack.com/archives/stackstorm/p1455568201000222
with:
```
E: Failed to fetch https://dl.bintray.com/stackstorm/trusty_staging/pool/stable/main/s/st2mistral/st2mistral_1.3.2-1_amd64.deb  Size mismatch
```

and there:
https://github.com/StackStorm/st2-packages/issues/130
```sh
Using https://packagecloud.io with token:******a7e9
Looking for repository at stackstorm/staging-stable... success!
Pushing ./test/st2mistral_1.3.0-1_amd64.deb... error:
filename: has already been taken
```
during PackageCloud uploads.

**Comment by lakshmi-kannan** [comment]
I think this is now done.
