### ISSUE TITLE
Use exec instead of script for mistral upstart

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2-packages#86]
We're currently using exec.  Functionally, I don't think there's a difference right now.  But script assumes a shell script per upstart documentation.

**Comment by lakshmi-kannan** [comment]
https://github.com/StackStorm/st2-packages/blob/master/packages/mistral/debian/mistral.upstart#L15

**Comment by dennybaa** [comment]
@m4dcoder could you explain your reason?
Both `script` and `exec` stanzas are valid and equally used invocation ways for upstart jobs

**Comment by dennybaa** [comment]
@m4dcoder we are not using exec **instead** of script. However **exec** should be the last one line in **script** stanza. This was fixed.
