### ISSUE TITLE
Info: DroneCI v0.4

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-packages#9]
So I've installed and played a lot with [Drone 0.4](https://github.com/drone/drone/tree/0.4.0/) on AWS. This version (under heavy development, but will be released soon) adds build `matrix` support, comparing to stable 0.3.
But I couldn't make Drone working as expected with our config. It's possible to fix it somehow via running `docker-compose` from docker inside docker, but some features are still unfinished.

#### Pros
* Self-hosted. That's awesome thing with wow-effect that you can host your own TravisCI-like system with nice UI and all the bells and whistles for free.
* Really loved their slick/minimal UI, and check that [API page design](http://readme.drone.io/docs/api/), - just wow! 
* Full control of everything: machine power/settings, even contribute to codebase and write your own plugins (in Go).
* Docker layers are cached on host's (main) machine, as usual when running Docker. Once docker image is downloaded - no need to re-download it again in future builds how it is in isolated Travis or Circle. This saves 2-4 minutes of build time in our case.

#### Cons
- No parallel builds. That was very surprising, but yes - builds in matrix are executed one-by-one. [Confirmed by core developers, this feature is not implemented yet](http://imgur.com/k8lEQCB). Coming in `v0.4.1`
- No option to run `deploy` when *all* builds in matrix succeeded. Eg. every build runs its independent deploy callback, no matter if others failed. [However something like that is planned in future](http://imgur.com/1iXugoB).
- Linked services logic was *slightly changed* in `v0.4` comparing to `v0.3`, making impossible to run our existing configuration/script without refactoring. Instead of making linked services available by `host`, [they are now all listen on `localhost`](http://readme.drone.io/docs/build/services.html). See [Core developer answer](http://imgur.com/2YhCytk). Because of this change we can't really sync `docker-compose` config with new `drone.yml` config, how it was in `0.3`.
- No native `docker-compose` configuration support. Since ^^ failed, I've tried to run `docker-compose` by sharing and re-using `docker.sock` of host machine. I could run `docker-compose`, but there is no easy way to share the contents of `$DRONE_DIR` which is working directory and redirect other variables from Drone build container. So the working solution will be dirty hack on dirty hack.
- No option via [API](http://readme.drone.io/docs/api/) to trigger the new build with specific parameters. Better API functionality is upcoming thing, as core developers said.

#### Try 1:
Trying new Drone v0.4 linked images format:
* [.drone.yml configuration used](https://github.com/armab/st2-packages/blob/e6350a88a1d62d6308550bfd96f9f458f593a35d/.drone.yml)
![](http://i.imgur.com/uVsKFgh.jpg)
See that services like `mongodb` are accessible via `127.0.0.1:27014`, not by host. Most probably it's made to be "user friendly" and easier in basic configurations, but our config is not that easy. I remember from my previous startup such things when we assumed "what is better" for user :cactus:  

#### Try 2:
Running `docker-compose` from docker: 
* [.drone.yml configuration used](https://github.com/armab/st2-packages/blob/e645caf490bf7bd379211640a0f7f55771b73cf9/.drone.yml)
![](http://i.imgur.com/9iE22zm.png)

Runs `docker-compose` from docker inside the docker.
Needs changing the script logic and sharing the working directory of current build.

#### References:
* [Drone v0.4 docs](http://readme.drone.io/docs/build/index.html) - pretty minimal for the moment.
* [Drone v0.4 codebase](https://github.com/drone/drone/tree/0.4.0/)
* Features/bugs to be done in [`v0.4.0`](https://github.com/drone/drone/milestones/v0.4.0) and [`v0.4.1`](https://github.com/drone/drone/milestones/v0.4.1) milestones.
* [API](http://readme.drone.io/docs/api/) - minimal, will be improved soon as core said.

----

So Drone 0.4 looks like definitely good thing in some future.
I really liked community support in their Gitter chat and overall it looks like it's developed by good guys (same feeling as with StackStorm), but overall system still missing needed features and it's still under heavy development.

Feels like if we start using it - we'll need to learn and hack in Golang to contribute fixes/extend our CI logic with plugins, what might be good thing from some point :) Same as we asking in #community to contribute st2.

I have some crazy ideas about Drone 0.3, will try it soon :hammer:

**Comment by dennybaa** [comment]
Awesome input. Lack of parallel builds ruins our major requirement - build for debian centos ubuntu in parallel.
Also build parameters pass-through is important...
Looking forward to hear about your crazy ideas about 0.3)

**Comment by dennybaa** [comment]
closing until better times of drone.
