### ISSUE TITLE
Remove specs for debian/ rpm/ except bundle and mistral

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2-packages#90]
cc: @lakshmi-kannan @kirilstrax @armab 
I suggest to think about **premature optimization**.

Honestly, we are not able to ship separate packages in the release. Now we are doing excessive work fixing files in st2* as well st2bundle packages, **not** all of that is only copy paste work, because it requires manual validation.
My personal feeling that what we are doing is  **premature optimization**, I also have a feeling that after this release we won't look at separate packages.

**Pros**
* We get component separation

**Cons**
* It's not real life scenario, since even you do some job on fixing package A. It won't work, since you need to propagate code from package A to st2bundle. Unless you've done work is in vain. (also #66)
* It's not fun validating init files for each service and st2bundle after copy-paste.
* It's simply duplication of efforts.

PS. component separation should be done in st2bundle package (logical enable/disable).
Please welcome, to discuss! But I'm asking you to be honest in terms of double effort and premature optimization.

**Comment by dennybaa** [comment]
I removed 5k of lines and it still works https://circleci.com/gh/StackStorm/st2-packages/243, heh. Why we should ship that fatty!?

**Comment by dennybaa** [comment]
as agreed with @dzimine it's a right move. issue is resolved in #163

**Comment by armab** [comment]
> I removed 5k of lines and it still works

Sounds like Windows

**Comment by armab** [comment]
Closing, since https://github.com/StackStorm/st2-packages/pull/163 solves it
