### ISSUE TITLE
add some dev dependencies to our packages

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2-packages#98]
* libpython-dev 
* libssl-dev
* libcffi-dev

@lakshmi-kannan @manasdk @Kami  also what else would you advise?

**Comment by Kami** [comment]
Do we plan to install those packages in all the containers or add it as dev dependency to st2bundle and other packages?

**Comment by armab** [comment]
As package dependencies, so they'll be installed automatically during `apt-get/yum install`.

As I remember from the history in Slack, they popped up when installing some packs from `st2contrib` (like `jira`).

**Comment by dennybaa** [comment]
definitely, upcoming Monday.
